# Generated by Django 5.1.2 on 2024-10-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RockClimb',
            new_name='Exercise',
        ),
    ]
